version: "3.3"

networks:
  - net:
    driver: overlay
    attachable: true

services:
  webapi:
    image: minhnq410/todo-api:latest
    ports:
      - "5000:5000"
    deploy:
      mode: replicated
      replicas: 1

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.42.0
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
    depends_on:
      - webapi
      