version: "3.3"

networks:
  - net:
    driver: overlay
    attachable: true

services:
  webapi:
    image: minhnq410/todo-api:latest
    ports:
      - "5000:5000"
    deploy:
      mode: replicated
      replicas: 2

  cadvisor:
    image: grc.io/cadvisor/cadvisor:v0.42.0
    ports:
      - "8080:8080"
    deploy:
      mode: global