version: "3.9"

services:
        todoapi:
                image: nqminh410/todo-api:sql
                ports:
                        - 5000:5000
                depends_on:
                        - db

        db:
                image: mcr.microsoft.com/mssql/server
                environment:
                        SA_PASSWORD: "1password2"
                        ACCEPT_EULA: "Y"
